CREATE TABLE RESERVE (
	NUM_SEQ	INTEGER	NOT NULL,
	COD_DC	VARCHAR(6)	NOT NULL,
	DESC_NAME	VARCHAR(10)	NOT NULL,
	DESC_COMPANY	VARCHAR(50),
	DESC_DEPT	VARCHAR(50),
	NUM_POST	VARCHAR(6),
	DESC_ADDR	VARCHAR(100),
	DESC_ADDR_1	VARCHAR(100),
	NUM_TEL	VARCHAR(15),
	DESC_EMAIL	VARCHAR(50),
	 CONSTRAINT PK_RESERVE PRIMARY KEY ( NUM_SEQ,COD_DC )
);